---
name: Docker Image CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Builds the alice-lg image

    steps:
      - uses: actions/checkout@v2

      - name: docker login
        id: dockerhub_login
        env:
          DOCKERHUB_PASSWORD: ${{ secrets.dockerhub_password }}
        run: |
          echo "::add-mask::$DOCKERHUB_PASSWORD"
          docker login --username "timrabl" --password "${DOCKERHUB_PASSWORD}"

      - name: docker build
        run: docker build -t timrabl/alice-lg:$(date %s) -f Dockerfile .

      - name: docker push
        run: docker push timrabl/alice-lg



