---
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build alice-lg
    steps:
      - name: Build alice-lg alpine docker image
        id: alpine_build
        uses: actions/build@v1
